In [17]:
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD

In [4]:
from sklearn.datasets import fetch_20newsgroups
categories = ['soc.religion.christian']
dataset = fetch_20newsgroups(subset='all',shuffle=True, random_state=42, categories=categories)
corpus = dataset.data

In [7]:
stopset = set(stopwords.words('english'))
stopset.update(['lt','p','/p','br','amp','quot','field','font','normal','span','0gx','rgb','style','51','spacing','text','helvetica','size','family','space','arial','height','lindent','letter','line','none','sans','serif','transform','line','variant','weight','times','strong','new','video','title','white','word','letter','roman','Opt','16','color','12','14','21','neve','apple','class',])

In [8]:
corpus[0]

u'From: sciysg@nusunix1.nus.sg (Yung Shing Gene)\nSubject: Mission Aviation Fellowship\nOrganization: National University of Singapore\nLines: 3\n\nHi,\n\tDoes anyone know anything about this group and what they\ndo? Any info would be appreciated. Thanks!\n'

In [9]:
vectorizer = TfidfVectorizer(stop_words=stopset,use_idf=True,ngram_range=(1,3))
X=vectorizer.fit_transform(corpus)

In [10]:
X[0]

<1x301759 sparse matrix of type '<type 'numpy.float64'>'
	with 72 stored elements in Compressed Sparse Row format>

In [11]:
print X[0]

  (0, 296340)	0.123882389819
  (0, 136773)	0.137053533366
  (0, 121217)	0.137053533366
  (0, 22469)	0.137053533366
  (0, 147609)	0.137053533366
  (0, 22212)	0.129348908299
  (0, 127146)	0.123882389819
  (0, 157376)	0.137053533366
  (0, 246575)	0.137053533366
  (0, 280276)	0.119642228669
  (0, 180323)	0.119642228669
  (0, 191744)	0.119642228669
  (0, 103620)	0.137053533366
  (0, 30216)	0.137053533366
  (0, 175125)	0.137053533366
  (0, 257962)	0.137053533366
  (0, 111385)	0.137053533366
  (0, 243273)	0.137053533366
  (0, 301544)	0.137053533366
  (0, 242492)	0.137053533366
  (0, 185638)	0.137053533366
  (0, 185647)	0.119642228669
  (0, 236540)	0.137053533366
  (0, 24033)	0.119642228669
  (0, 296338)	0.119642228669
  :	:
  (0, 265758)	0.0686976091148
  (0, 24016)	0.0975401027236
  (0, 296233)	0.0301177950438
  (0, 136715)	0.0890597804242
  (0, 121105)	0.0600617447998
  (0, 22354)	0.0547611832123
  (0, 147557)	0.0374501528559
  (0, 22027)	0.0504212740987
  (0, 127144)	0.0843689591761
  (0, 

In [12]:
X.shape

(997, 301759)

In [21]:
lsa=TruncatedSVD(n_components=30,n_iter=100)
lsa.fit(X)

TruncatedSVD(algorithm='randomized', n_components=30, n_iter=100,
       random_state=None, tol=0.0)

In [23]:
lsa.components_[0]

array([ 0.01487088,  0.00700224,  0.00128836, ...,  0.00025395,
        0.00025395,  0.00025395])

In [24]:
terms=vectorizer.get_feature_names()
for i, comp in enumerate (lsa.components_):
    termsInComp=zip(terms,comp)
    sortedTerms=sorted(termsInComp,key=lambda X:X[1],reverse = True)[:10]
    print "Concept %d:"%i
    for term in sortedTerms:
        print term[0]
        print""

Concept 0:
god

edu

one

jesus

would

people

sin

church

us

com

Concept 1:
god

christ

00 08 15

time

life

jesus

point

believe

said

human

Concept 2:
god

truth

organization

us

homosexual

would

law

paul

faith

com

Concept 3:
hell

say

lines

writes

christ

organization

00 08 15

since

heaven

com

Concept 4:
god

1993

without

edu

know

could

good

rutgers

law

use

Concept 5:
faith

even

christian

religion

apr

love

also

believe

way

00 08 27

Concept 6:
00 08 10

faith

people

sin

however

us

make

church

wrong

1993

Concept 7:
christ

truth

church

sin

us

rutgers

question

00 08 10

faith

shall

Concept 8:
jesus

son

subject re

people

mary

also

christ

need

eternal

organization

Concept 9:
know

christ

way

00 08 27

lord

church

psalms

think

00 08 44

doesn

Concept 10:
good

also

com

would

come

00 08 44

even

00 08 27

writes

true

Concept 11:
jesus

even

rutgers edu

edu

00 08 10

subject re

lord

re

subject

peopl

In [25]:
corpus[1]

u"From: whitsebd@nextwork.rose-hulman.edu (Bryan Whitsell)\nSubject: Re: Satan and TV\nReply-To: whitsebd@nextwork.rose-hulman.edu\nOrganization: News Service at Rose-Hulman\nLines: 14\n\nIn article <May.9.05.41.06.1993.27543@athos.rutgers.edu>  \nsalaris@niblick.ecn.purdue.edu (Rrrrrrrrrrrrrrrabbits) writes:\n> MTV controls what bands are popular, no matter how bad they are.  In fact, it is  \n>better to be politically correct - like U2, Madonna - than to have any musical  \n>talent. \n> Steven C. Salaris                \n \nInteresting idea.  \nRegular televeision seems to do this sort of thing too with politically correct  \nshows.\n\n\nIn Christ's Love\nBryan \n"

In [26]:
vectorizer = TfidfVectorizer(stop_words=stopset,use_idf=True,ngram_range=(1,3))
X=vectorizer.fit_transform(corpus)

In [27]:
X[0]

<1x301759 sparse matrix of type '<type 'numpy.float64'>'
	with 72 stored elements in Compressed Sparse Row format>

In [28]:
print X[0]

  (0, 296340)	0.123882389819
  (0, 136773)	0.137053533366
  (0, 121217)	0.137053533366
  (0, 22469)	0.137053533366
  (0, 147609)	0.137053533366
  (0, 22212)	0.129348908299
  (0, 127146)	0.123882389819
  (0, 157376)	0.137053533366
  (0, 246575)	0.137053533366
  (0, 280276)	0.119642228669
  (0, 180323)	0.119642228669
  (0, 191744)	0.119642228669
  (0, 103620)	0.137053533366
  (0, 30216)	0.137053533366
  (0, 175125)	0.137053533366
  (0, 257962)	0.137053533366
  (0, 111385)	0.137053533366
  (0, 243273)	0.137053533366
  (0, 301544)	0.137053533366
  (0, 242492)	0.137053533366
  (0, 185638)	0.137053533366
  (0, 185647)	0.119642228669
  (0, 236540)	0.137053533366
  (0, 24033)	0.119642228669
  (0, 296338)	0.119642228669
  :	:
  (0, 265758)	0.0686976091148
  (0, 24016)	0.0975401027236
  (0, 296233)	0.0301177950438
  (0, 136715)	0.0890597804242
  (0, 121105)	0.0600617447998
  (0, 22354)	0.0547611832123
  (0, 147557)	0.0374501528559
  (0, 22027)	0.0504212740987
  (0, 127144)	0.0843689591761
  (0, 

In [29]:
X.shape

(997, 301759)

In [30]:
lsa=TruncatedSVD(n_components=30,n_iter=100)
lsa.fit(X)

TruncatedSVD(algorithm='randomized', n_components=30, n_iter=100,
       random_state=None, tol=0.0)

In [31]:
lsa.components_[0]

array([ 0.01487088,  0.00700224,  0.00128836, ...,  0.00025395,
        0.00025395,  0.00025395])

In [32]:
terms=vectorizer.get_feature_names()
for i, comp in enumerate (lsa.components_):
    termsInComp=zip(terms,comp)
    sortedTerms=sorted(termsInComp,key=lambda X:X[1],reverse = True)[:10]
    print "Concept %d:"%i
    for term in sortedTerms:
        print term[0]
        print""

Concept 0:
god

edu

one

jesus

would

people

sin

church

us

com

Concept 1:
homosexuality

homosexual

people

com

bible

say

way

faith

says

another

Concept 2:
god

jesus

00 08 10

christ

00 08 27

00 08 22

time

really

lord

doctrine

Concept 3:
god

us

00 08 33

sin

one

michael

bible

00 08 44

hell

00 08 04

Concept 4:
bible

sin

homosexuality

first

good

lines

re

believe

edu

mean

Concept 5:
think

hell

00 08 33

one

christ

edu

come

subject

mary

homosexuality

Concept 6:
sin

say

love

10

life

subject

mean

believe

mary

00 08 33

Concept 7:
like

think

believe

christian

question

would

read

bible

jesus

christians

Concept 8:
com

god

would

christianity

us

things

article

way

law

00 08 22

Concept 9:
jesus

church

00 08 44

also

man

must

00 08 33

say

hell

right

Concept 10:
jesus

edu

question

christianity

catholic

subject re

let

00 08 27

many

us

Concept 11:
also

first

things

one

church

could

way

want

00 0

In [33]:
corpus[2]

u'From: whitsebd@nextwork.rose-hulman.edu (Bryan Whitsell)\nSubject: Re: "Accepting Jesus in your heart..."\nReply-To: whitsebd@nextwork.rose-hulman.edu\nOrganization: Computer Science Department at Rose-Hulman\nLines: 20\n\nstuff deleted ...\n\n> Religion (especially Christianity) is nothing more than a DRUG.\n> Some people use drugs as an escape from reality.  Christians inject\n> themselves with jeezus and live with that high. \n \nYour logic is falty.  If Christianity is a DRUG, and once we die we\ndie, then why would you be reluctant to embrase this drug so that\nwhile you are alive you enjoy yourself.\n\nI also question your overall motives for posting this article.  Why\nwould you waste your presious fews seconds on this earth posting your\nopinon to a group that will generally reject it.\n\nIf you die, never having acepting Christ as your savior, I hope you\nhave a fantastic life that it is all you evver dreamed because it is\nal of heaven you will ever know.\n\nIn Christ\'s Lo

In [34]:
vectorizer = TfidfVectorizer(stop_words=stopset,use_idf=True,ngram_range=(1,3))
X=vectorizer.fit_transform(corpus)

In [35]:
X[0]

<1x301759 sparse matrix of type '<type 'numpy.float64'>'
	with 72 stored elements in Compressed Sparse Row format>

In [36]:
print X[0]

  (0, 296340)	0.123882389819
  (0, 136773)	0.137053533366
  (0, 121217)	0.137053533366
  (0, 22469)	0.137053533366
  (0, 147609)	0.137053533366
  (0, 22212)	0.129348908299
  (0, 127146)	0.123882389819
  (0, 157376)	0.137053533366
  (0, 246575)	0.137053533366
  (0, 280276)	0.119642228669
  (0, 180323)	0.119642228669
  (0, 191744)	0.119642228669
  (0, 103620)	0.137053533366
  (0, 30216)	0.137053533366
  (0, 175125)	0.137053533366
  (0, 257962)	0.137053533366
  (0, 111385)	0.137053533366
  (0, 243273)	0.137053533366
  (0, 301544)	0.137053533366
  (0, 242492)	0.137053533366
  (0, 185638)	0.137053533366
  (0, 185647)	0.119642228669
  (0, 236540)	0.137053533366
  (0, 24033)	0.119642228669
  (0, 296338)	0.119642228669
  :	:
  (0, 265758)	0.0686976091148
  (0, 24016)	0.0975401027236
  (0, 296233)	0.0301177950438
  (0, 136715)	0.0890597804242
  (0, 121105)	0.0600617447998
  (0, 22354)	0.0547611832123
  (0, 147557)	0.0374501528559
  (0, 22027)	0.0504212740987
  (0, 127144)	0.0843689591761
  (0, 

In [37]:
X.shape

(997, 301759)

In [39]:
lsa=TruncatedSVD(n_components=27,n_iter=100)
lsa.fit(X)

TruncatedSVD(algorithm='randomized', n_components=27, n_iter=100,
       random_state=None, tol=0.0)

In [40]:
lsa.components_[0]

array([ 0.01487088,  0.00700224,  0.00128836, ...,  0.00025395,
        0.00025395,  0.00025395])

In [41]:
terms=vectorizer.get_feature_names()
for i, comp in enumerate (lsa.components_):
    termsInComp=zip(terms,comp)
    sortedTerms=sorted(termsInComp,key=lambda X:X[1],reverse = True)[:10]
    print "Concept %d:"%i
    for term in sortedTerms:
        print term[0]
        print""

Concept 0:
god

edu

one

jesus

would

people

sin

church

us

com

Concept 1:
god

lord

hell

love

must

11

00 08 04

life

thing

00 08 07

Concept 2:
com

article

like

writes

christian

christianity

christians

point

subject

hell

Concept 3:
homosexuality

homosexual

things

people

jesus

subject

think

marriage

much

seems

Concept 4:
jesus

one

sin

church

00 08 15

things

mary

make

00 08 27

think

Concept 5:
sin

jesus

subject

like

homosexuality

never

must

lord

would

many

Concept 6:
would

com

say

1993

answer

us

christian

00 08 35

re

apr

Concept 7:
jesus

god

00 08 47

way

paul

rutgers edu

people

university

bible

anyone

Concept 8:
god

church

article

way

bible

re

however

00 08 33

one

00 08 15

Concept 9:
com

bible

believe

church

christ

mary

say

truth

first

subject

Concept 10:
jesus

life

think

christ

re

christianity

00 08 22

faith

says

understand

Concept 11:
bible

faith

people

com

may

hell

never

rutg